### ISSUE TITLE
scanpy-scripts will not install, conflicting scipy version requirements

### ISSUE THREAD

**Issue by mathog** [ebi-gene-expression-group/scanpy-scripts#81]
I cannot successfully install scanpy-scripts even in a venv.  This is on CentOS 8, but that is probably irrelevant.  The issue is that there are conflicting requirements for scipy, which, depending on how it is installed,
will end up with a message like this:

`  #ERROR: umap-learn 0.4.6 has requirement scipy>=1.3.1, but you'll have scipy 1.2.3 which is incompatible.`

Example commands:

```
  cd /usr/common/lib/python3.6/Envs
  rm -rf ~/.cache/pip #make download clearer
  python3 -m venv scanpy_scripts
  source scanpy_scripts/bin/activate
  python -m pip install -U pip
  python -m pip install scanpy_scripts
  #same error
  python -m pip install -U setuptools #39.2 -> 47.3.1
  python -m pip install scanpy_scripts
  #same error
  python -m pip install -U wheel
  python -m pip install scanpy_scripts
  #same error
  echo $PYTHONPATH
  #is blank
```
If one installs "johnnydep" with pip3 in a venv and then run:

`johnnydep scanpy-scripts
`
it gives a ton of details, but the bottom line is the final error:

```
ERROR: No matching distribution found for scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0
pip._internal.exceptions.DistributionNotFound: No matching distribution found for scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-vvv', '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--pro
gress-bar=off', 'scipy<1.3.0,>=0.19.1,>=1.0,>=1.0.1,>=1.2.0,>=1.3.1,~=1.0']' returned non-zero exit status 1.
```
That is, it cannot match both <1.3.0 and >= 1.3.1 for scipy.

**Comment by pinin4fjords** [comment]
Thanks for the issue report @mathog, sorry for the slow response. Working on a fix at https://github.com/ebi-gene-expression-group/scanpy-scripts/pull/83, see also https://github.com/bioconda/bioconda-recipes/pull/23731.

**Comment by pinin4fjords** [comment]
PyPi package version 0.2.11 and Conda package >=0.2.10 should resolve this.

**Comment by mathog** [comment]
It still does not work for me on CentOS 8:

python3 -m venv scanpy-scripts
source scanpy-scripts/bin/activate
pip3 install scanpy-scripts 2>&1 | tee /tmp/install_ss.log 
#fails in louvain

log file attached

[install_ss.log](https://github.com/ebi-gene-expression-group/scanpy-scripts/files/5030173/install_ss.log)

**Comment by mathog** [comment]
Note, it tried to install louvain 0.6.1. ( louvain 0.7.0 has installed successfully before on this system.)  Before louvain installed igraph 0.8.2 had been installed.  Then louvain wanted something from it and tried to build igraph 0.7.1 on its own, which is probably why everything blew up.

 johnnydep --output-format pinned scanpy-scripts

exploded.  This is unusual.  Usually it spots a conflict, but in this case it appears to have let louvain try to install the other igraph version, and that crashed as before.

**Comment by pinin4fjords** [comment]
Sorry @mathog , but I'm unable to replicate your issues:

```
pip install scanpy-scripts==0.2.11
Collecting scanpy-scripts==0.2.11
  Using cached scanpy_scripts-0.2.11-py3-none-any.whl (43 kB)
Collecting pandas
  Downloading pandas-1.1.0-cp38-cp38-manylinux1_x86_64.whl (10.3 MB)
     |████████████████████████████████| 10.3 MB 9.7 MB/s 
Collecting h5py<2.10
  Using cached h5py-2.9.0-cp38-cp38-manylinux1_x86_64.whl (2.8 MB)
Collecting Click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting anndata<0.6.20
  Using cached anndata-0.6.19-py3-none-any.whl (44 kB)
Collecting louvain<=0.6.1
  Using cached louvain-0.6.1.tar.gz (84 kB)
Processing ./.cache/pip/wheels/b8/f4/2a/2a6af3129d6d3f1fea59d476fd84326629e4075a73f5f35b1b/scipy-1.2.3-cp38-cp38-linux_x86_64.whl
Collecting leidenalg
  Using cached leidenalg-0.8.1-cp38-cp38-manylinux2010_x86_64.whl (2.4 MB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Processing ./.cache/pip/wheels/62/fc/a5/9a3b34382cf75f60f8840dba221425dbc1530ad2a5bd2786b8/MulticoreTSNE-0.1-cp38-cp38-linux_x86_64.whl
Processing ./.cache/pip/wheels/d8/5b/bb/addda229a9f418417d287055c1daf4acf4c6b074e2d38dfcfa/umap_learn-0.3.10-py3-none-any.whl
Collecting matplotlib
  Using cached matplotlib-3.3.0-1-cp38-cp38-manylinux1_x86_64.whl (11.5 MB)
Collecting scanpy==1.4.3
  Using cached scanpy-1.4.3-py3-none-any.whl (2.1 MB)
Processing ./.cache/pip/wheels/7e/e8/4b/2df3c7132dc778bb7d435eca351ee2167a45559fead841691b/loompy-2.0.17-py3-none-any.whl
Collecting numpy>=1.15.4
  Using cached numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting natsort
  Using cached natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting python-igraph>=0.7.1.0
  Using cached python_igraph-0.8.2-cp38-cp38-manylinux2010_x86_64.whl (3.2 MB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cffi
  Using cached cffi-1.14.1-cp38-cp38-manylinux1_x86_64.whl (409 kB)
Collecting scikit-learn>=0.16
  Using cached scikit_learn-0.23.2-cp38-cp38-manylinux1_x86_64.whl (6.8 MB)
Collecting numba>=0.37
  Using cached numba-0.50.1-cp38-cp38-manylinux2014_x86_64.whl (3.6 MB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl (92 kB)
Collecting patsy
  Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)
Collecting seaborn
  Using cached seaborn-0.10.1-py3-none-any.whl (215 kB)
Collecting joblib
  Using cached joblib-0.16.0-py3-none-any.whl (300 kB)
Collecting networkx
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting tables
  Using cached tables-3.6.1-cp38-cp38-manylinux1_x86_64.whl (4.3 MB)
Collecting tqdm
  Using cached tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
Collecting statsmodels
  Using cached statsmodels-0.11.1-cp38-cp38-manylinux1_x86_64.whl (8.7 MB)
Requirement already satisfied: setuptools in /nfs/production3/ma/home/jmanning/software/conda/envs/scanpy-pypi-test/lib/python3.8/site-packages (from loompy<3.0.0,>=2.0.0->scanpy-scripts==0.2.11) (49.2.1.post20200802)
Collecting texttable>=1.6.2
  Using cached texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting llvmlite<0.34,>=0.33.0.dev0
  Using cached llvmlite-0.33.0-cp38-cp38-manylinux1_x86_64.whl (18.3 MB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting numexpr>=2.6.2
  Using cached numexpr-2.7.1-cp38-cp38-manylinux1_x86_64.whl (164 kB)
Building wheels for collected packages: louvain
  Building wheel for louvain (setup.py) ... done
  Created wheel for louvain: filename=louvain-0.6.1-cp38-cp38-linux_x86_64.whl size=927739 sha256=5887c888510de06b9113e4e5b1ad733ffb47c941f2c03dd8bc95659e6442f4fe
  Stored in directory: <PATH>/.cache/pip/wheels/05/5c/d9/45d939cdffe9da26671a661923778a91c38b3690fe9726c096
Successfully built louvain
Installing collected packages: numpy, six, python-dateutil, pytz, pandas, h5py, Click, natsort, scipy, anndata, texttable, python-igraph, louvain, leidenalg, pyparsing, packaging, pycparser, cffi, MulticoreTSNE, joblib, threadpoolctl, scikit-learn, llvmlite, numba, umap-learn, cycler, pillow, kiwisolver, matplotlib, patsy, seaborn, decorator, networkx, numexpr, tables, tqdm, statsmodels, scanpy, loompy, scanpy-scripts
Successfully installed Click-7.1.2 MulticoreTSNE-0.1 anndata-0.6.19 cffi-1.14.1 cycler-0.10.0 decorator-4.4.2 h5py-2.9.0 joblib-0.16.0 kiwisolver-1.2.0 leidenalg-0.8.1 llvmlite-0.33.0 loompy-2.0.17 louvain-0.6.1 matplotlib-3.3.0 natsort-7.0.1 networkx-2.4 numba-0.50.1 numexpr-2.7.1 numpy-1.19.1 packaging-20.4 pandas-1.1.0 patsy-0.5.1 pillow-7.2.0 pycparser-2.20 pyparsing-2.4.7 python-dateutil-2.8.1 python-igraph-0.8.2 pytz-2020.1 scanpy-1.4.3 scanpy-scripts-0.2.11 scikit-learn-0.23.2 scipy-1.2.3 seaborn-0.10.1 six-1.15.0 statsmodels-0.11.1 tables-3.6.1 texttable-1.6.2 threadpoolctl-2.1.0 tqdm-4.48.2 umap-learn-0.3.10
```

Any ideas @nh3 ?

**Comment by mathog** [comment]
Mine used python3.6, yours used python3.8.

Have you tried it on the older python?

(Seems like a long shot, but it is a difference.)

Thanks.

**Comment by pinin4fjords** [comment]
All good on 3.6:

```
> pip install scanpy-scripts==0.2.11
Collecting scanpy-scripts==0.2.11
  Downloading scanpy_scripts-0.2.11-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 256 kB/s 
Collecting louvain<=0.6.1
  Downloading louvain-0.6.1.tar.gz (84 kB)
     |████████████████████████████████| 84 kB 275 kB/s 
Collecting h5py<2.10
  Downloading h5py-2.9.0-cp36-cp36m-manylinux1_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 14.2 MB/s 
Collecting pandas
  Downloading pandas-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 26.3 MB/s 
Collecting leidenalg
  Downloading leidenalg-0.8.1-cp36-cp36m-manylinux2010_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 44.0 MB/s 
Collecting Click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 218 kB/s 
Collecting scipy<1.3.0,>=1.2.0
  Downloading scipy-1.2.3-cp36-cp36m-manylinux1_x86_64.whl (24.8 MB)
     |████████████████████████████████| 24.8 MB 7.0 MB/s 
Collecting scanpy==1.4.3
  Downloading scanpy-1.4.3-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 47.4 MB/s 
Collecting matplotlib
  Downloading matplotlib-3.3.0-1-cp36-cp36m-manylinux1_x86_64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB 47.9 MB/s 
Collecting MulticoreTSNE
  Downloading MulticoreTSNE-0.1.tar.gz (20 kB)
Collecting anndata<0.6.20
  Downloading anndata-0.6.19-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 1.9 MB/s 
Collecting loompy<3.0.0,>=2.0.0
  Downloading loompy-2.0.17.tar.gz (32 kB)
Collecting umap-learn<0.4.0
  Downloading umap-learn-0.3.10.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 3.0 MB/s 
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting python-igraph>=0.7.1.0
  Downloading python_igraph-0.8.2-cp36-cp36m-manylinux2010_x86_64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 105.9 MB/s 
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting numpy>=1.7
  Downloading numpy-1.19.1-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 53.5 MB/s 
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 42.9 MB/s 
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 46.7 MB/s 
Collecting patsy
  Downloading patsy-0.5.1-py2.py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 46.6 MB/s 
Collecting natsort
  Downloading natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting seaborn
  Downloading seaborn-0.10.1-py3-none-any.whl (215 kB)
     |████████████████████████████████| 215 kB 45.9 MB/s 
Collecting statsmodels
  Downloading statsmodels-0.11.1-cp36-cp36m-manylinux1_x86_64.whl (8.7 MB)
     |████████████████████████████████| 8.7 MB 43.6 MB/s 
Collecting tables
  Downloading tables-3.6.1-cp36-cp36m-manylinux1_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 46.1 MB/s 
Collecting joblib
  Downloading joblib-0.16.0-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 153.6 MB/s 
Collecting scikit-learn>=0.19.1
  Downloading scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 45.1 MB/s 
Collecting numba>=0.41.0
  Downloading numba-0.50.1-cp36-cp36m-manylinux2014_x86_64.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 43.2 MB/s 
Collecting networkx
  Downloading networkx-2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 44.1 MB/s 
Collecting tqdm
  Downloading tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 704 kB/s 
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 42.6 MB/s 
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 876 kB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 5.3 MB/s 
Collecting cffi
  Downloading cffi-1.14.1-cp36-cp36m-manylinux1_x86_64.whl (400 kB)
     |████████████████████████████████| 400 kB 57.4 MB/s 
Requirement already satisfied: setuptools in <PATH>/lib/python3.6/site-packages (from loompy<3.0.0,>=2.0.0->scanpy-scripts==0.2.11) (49.2.1.post20200802)
Collecting texttable>=1.6.2
  Downloading texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting numexpr>=2.6.2
  Downloading numexpr-2.7.1-cp36-cp36m-manylinux1_x86_64.whl (162 kB)
     |████████████████████████████████| 162 kB 103.2 MB/s 
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting llvmlite<0.34,>=0.33.0.dev0
  Downloading llvmlite-0.33.0-cp36-cp36m-manylinux1_x86_64.whl (18.3 MB)
     |████████████████████████████████| 18.3 MB 24.2 MB/s 
Collecting decorator>=4.3.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 137.2 MB/s 
Building wheels for collected packages: louvain, MulticoreTSNE, loompy, umap-learn
  Building wheel for louvain (setup.py) ... done
  Created wheel for louvain: filename=louvain-0.6.1-cp36-cp36m-linux_x86_64.whl size=926547 sha256=353be75d7d29e5d0f6b80ca7eacaa5f8da18b8fcbd6b5ae23784c7df4741b52e
  Stored in directory: <PATH>/.cache/pip/wheels/00/9f/0b/58379941fc571996219ce027270ad7801c20f37cd2dd8c824c
  Building wheel for MulticoreTSNE (setup.py) ... done
  Created wheel for MulticoreTSNE: filename=MulticoreTSNE-0.1-cp36-cp36m-linux_x86_64.whl size=65577 sha256=dc52fdcbb1bced2f5b7afbc23decbeab177dd6cc2ae56b3103b4510adeec2476
  Stored in directory: <PATH>/.cache/pip/wheels/78/46/d6/b95563cc72a9c84e95d5f047d9e7f727521495ddc49030fa23
  Building wheel for loompy (setup.py) ... done
  Created wheel for loompy: filename=loompy-2.0.17-py3-none-any.whl size=38394 sha256=42528dc0ae580b2c39391ce4af79222b792561a3f1bc48abfab65cf2c61b2e71
  Stored in directory: <PATH>/.cache/pip/wheels/9c/da/fb/1ae6240633ac7588f24d97e331f2880ddaf724e1702d163e18
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.3.10-py3-none-any.whl size=38881 sha256=3d589830593848d1722e3e29fd2aa1955f45e5b2136bdc0a375c1d541cd52e4d
  Stored in directory: <PATH>/.cache/pip/wheels/1b/69/69/91e19c0578b1740a6358f5db2c2dcc5af5b04360c3c9066b26
Successfully built louvain MulticoreTSNE loompy umap-learn
Installing collected packages: texttable, python-igraph, louvain, six, numpy, h5py, pytz, python-dateutil, pandas, leidenalg, Click, scipy, patsy, natsort, cycler, pillow, kiwisolver, pyparsing, matplotlib, seaborn, statsmodels, numexpr, tables, joblib, threadpoolctl, scikit-learn, llvmlite, numba, decorator, networkx, umap-learn, tqdm, anndata, scanpy, pycparser, cffi, MulticoreTSNE, loompy, packaging, scanpy-scripts
Successfully installed Click-7.1.2 MulticoreTSNE-0.1 anndata-0.6.19 cffi-1.14.1 cycler-0.10.0 decorator-4.4.2 h5py-2.9.0 joblib-0.16.0 kiwisolver-1.2.0 leidenalg-0.8.1 llvmlite-0.33.0 loompy-2.0.17 louvain-0.6.1 matplotlib-3.3.0 natsort-7.0.1 networkx-2.4 numba-0.50.1 numexpr-2.7.1 numpy-1.19.1 packaging-20.4 pandas-1.1.0 patsy-0.5.1 pillow-7.2.0 pycparser-2.20 pyparsing-2.4.7 python-dateutil-2.8.1 python-igraph-0.8.2 pytz-2020.1 scanpy-1.4.3 scanpy-scripts-0.2.11 scikit-learn-0.23.2 scipy-1.2.3 seaborn-0.10.1 six-1.15.0 statsmodels-0.11.1 tables-3.6.1 texttable-1.6.2 threadpoolctl-2.1.0 tqdm-4.48.2 umap-learn-0.3.10```

**Comment by mathog** [comment]
Figured it out.  The louvain build depends on the existence of igraph shared libraries AND the install was from a nonpriv'd account.  The igraph libraries are not installed by default on CentOS 8, in fact, there is no standard RPM for them.  Because the account was not privileged (I think) the automatic build from source failed because that account count not write to the needed directories.

So
```

#as root
wget https://download.fedoraproject.org/pub/fedora/linux/updates/32/Everything/SRPMS/Packages/i/igraph-0.8.2-1.fc32.src.rpm
rpmbuild --rebuild igraph-0.8.2-1.fc32.src.rpm
cd ~/rpmbuild/RPMS/x86_64
dnf -y install igraph-0.8.2-1.el8.x86_64.rpm igraph-devel-0.8.2-1.el8.x86_64.rpm

#as modules (unpriv'd account), in the existing venv
pip3 install scanpy-scripts
#worked!
```

So, there is an undocumented dependency on that library  (libigraph.so), and those could not be resolved, apparently, from an unpriv'd account automatically.

**Comment by nh3** [comment]
I think this could be a perfect example showing the utility of `conda`, which doesn't require root privilege and automatically solves and installs all dependencies that have been tested to work in a minimal environment. On the contrary, `pip` doesn't solve dependencies outside python and the correctness of dependencies/installation is not tested.
